In [1]:
import pandas as pd
import numpy as np

csv_path = 'rf_light_throughput_cv_summary.csv'

df = pd.read_csv(csv_path)
df

,dataset,n_samples,mean_R2,mean_MAE,mean_RMSE,mean_MRE(%),std_R2,std_MAE,std_RMSE,std_MRE(%)
0,data_EleutherAI_gpt-neox-20b,89719,0.994453,14.731459,43.455400,24.593194,0.002251,0.776541,9.890531,1.356892
1,data_Salesforce_codegen2-16B,6025,0.973733,12.270486,64.437178,21.188846,0.014727,2.767384,24.563784,2.108456
2,data_bigcode_starcoder,134772,0.995274,14.890953,42.033483,21.148057,0.001779,0.693642,9.476576,0.574710
3,data_bigscience_mt0-xxl,10706,0.987888,13.904727,57.691499,17.789815,0.005355,1.759417,17.605439,1.057250
4,data_google_flan-t5-xl,138299,0.995029,10.116215,30.441100,27.926744,0.001216,0.281341,4.433422,1.381022
5,data_google_flan-t5-xxl,77922,0.993027,9.391039,32.300078,26.502265,0.005928,0.565635,12.146636,1.305539
6,data_google_flan-ul2,45856,0.991003,9.206237,34.820006,23.406108,0.006160,0.571184,12.398398,1.286807
7,data_ibm_mpt-7b-instruct2,19086,0.990859,17.768015,72.328823,26.155413,0.005602,2.068647,26.444528,1.433732
8,data_llama-13b,119291,0.995224,14.944779,43.444249,23.128336,0.001741,0.536320,9.254051,0.702345
9,data_llama-7b,171218,0.995653,18.636039,52.215250,23.249379,0.001609,0.586079,9.900975,0.756858

In [2]:
df_formatted = df.copy()

df_formatted["n_samples"] = df_formatted["n_samples"].map("{:,}".format)

for col in [
    "mean_R2", "std_R2",
    "mean_MAE", "std_MAE",
    "mean_RMSE", "std_RMSE",
    "mean_MRE(%)", "std_MRE(%)"
]:
    df_formatted[col] = df_formatted[col].astype(float).round(3)

df_formatted

,dataset,n_samples,mean_R2,mean_MAE,mean_RMSE,mean_MRE(%),std_R2,std_MAE,std_RMSE,std_MRE(%)
0,data_EleutherAI_gpt-neox-20b,"89,719",0.994,14.731,43.455,24.593,0.002,0.777,9.891,1.357
1,data_Salesforce_codegen2-16B,"6,025",0.974,12.270,64.437,21.189,0.015,2.767,24.564,2.108
2,data_bigcode_starcoder,"134,772",0.995,14.891,42.033,21.148,0.002,0.694,9.477,0.575
3,data_bigscience_mt0-xxl,"10,706",0.988,13.905,57.691,17.790,0.005,1.759,17.605,1.057
4,data_google_flan-t5-xl,"138,299",0.995,10.116,30.441,27.927,0.001,0.281,4.433,1.381
5,data_google_flan-t5-xxl,"77,922",0.993,9.391,32.300,26.502,0.006,0.566,12.147,1.306
6,data_google_flan-ul2,"45,856",0.991,9.206,34.820,23.406,0.006,0.571,12.398,1.287
7,data_ibm_mpt-7b-instruct2,"19,086",0.991,17.768,72.329,26.155,0.006,2.069,26.445,1.434
8,data_llama-13b,"119,291",0.995,14.945,43.444,23.128,0.002,0.536,9.254,0.702
9,data_llama-7b,"171,218",0.996,18.636,52.215,23.249,0.002,0.586,9.901,0.757